// <auto-generated />
namespace Shop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201910311124122_AddPassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
